### ISSUE TITLE
Open Source Tools For Network Management

### ISSUE THREAD

**Issue by italobusi** [danielkinguk/transport-nbi#54]
An overview of some open-source tools has been provided during IETF 103 RTGWG meeting:
 
https://datatracker.ietf.org/meeting/103/materials/slides-103-rtgwg-sessa-open-source-tools-for-network-management-01

It woudl be worthwhile checking whether there are tools which may be useful for the DT work

For example, the presentation mentions a Libyang tool which “allows you to load and validate the YANG schemas and data”

- [ ] Pending actions from DT call on January 16, 2019: https://github.com/danielkinguk/transport-nbi/issues/54#issuecomment-454832127
- [ ] Pending actions from DT call on February 20, 2019: https://github.com/danielkinguk/transport-nbi/issues/54#issuecomment-465606866

Based on discussion in Prague, this could be spun out into a new effort: https://github.com/danielkinguk/transport-nbi/blob/master/Meetings/2019-03-23-29-IETF104/minutes-transport-nbi-dt-2019-03-27-ietf104.md

**Comment by GianmarcoBruno** [comment]
Here is a quick comparison between pyang 1.7.1 and libyang (yanglint 0.16.94).
Comparison may be a bit unfair as the first dates back to April 2016 and the second to about September 2018.

# Approach & Language
Pyang is a python library having at its core XML transformations to perform validations.
It provides a set of commands to be called from shell or from scripts as we do.
Libyang is written in C and it is exposed in two ways:
-	As a library to be called from other programs
-	yanglint - An interactive shell with some commands to add/print modules and perform validations of documents.

# Experiments
So far I have built libyang from source and played with it. No binary seems available but installation goes smooth.
You may need to install some development libraries if not already present in your environment.
I successfully validated some toy models and documents produced in the transport NBI DT, i.e.:
https://github.com/GianmarcoBruno/json-yang/tree/master/tests/dishwasher
and
https://github.com/GianmarcoBruno/transport-nbi-backoffice/tree/master/use-case-1-topology-data

I tested intentionally well- and badly-formed documents with the same outcomes so far from the two tools.
Error messages from libyang are slightly more helpful to the user than those from pyang.

Libyang appears very much faster than pyang and this is consistent with the approach of using compiled code from C instead of python/XSLT.

Libyang, when used as yanglint, may be a bit more rigid than pyag as it requires interactive execution instead of just scripting. Perhaps this can be circumvented.

I haven’t still found a way to validate sub-tree or individual leaves - neither NETCONF nor RESTCONF messages.
It seems that libyang only deals with documents representing the full datastore as pyang does.
libyang seems to deal with features.

# further work
- increase the test cases to see inconsistent results
- work with features in libyang
- validate document subsets instead of the full one

**Comment by italobusi** [comment]
Discussed during the DT call on January 16, 2019:

https://github.com/danielkinguk/transport-nbi/tree/master/Meetings/2019-01-16

**Actions (Gianmarco):**
- [ ] Check that libyang does not have the issues identified with pyang validation
- [ ] Update the validation toolchain to use libyang instead of pyang 
- [ ] Update Appendix A of the Applicability-Statement I-D after libyang is used

**Action (Italo):**
- [ ] Send a mail to Benoit to check if he has a preference (pyang, libyang or both) and also whether he knows how are IETF I-D JSON examples typically validated

**Comment by italobusi** [comment]
DT call on February 22, 2019:

Gianmarco has checked that libyang validates the JSON code taking the features into account while pyang assumes that all the features are supported

In order to use yanglint on Windows, Gianmarco has prepared a version which compile it within a Docker container:

https://github.com/GianmarcoBruno/docker-yanglint

A Docket container can be installed on Windows 10 using [Docker Desktop (https://www.docker.com/products/docker-desktop)]
